### ISSUE TITLE
[Enhancements] TODO List

### ISSUE THREAD

**Issue by Alphanum404** [Alphanum404/SiPiRang#1]
# TODO List
- [x] Add Index Dashboard
- [x] Update List Admin Dashboard
- [x] Update List Users Dashboard
- [x] Add validation to prevent renting already occupied rooms
- [x] Update List Room Dashboard
- [ ] Add Name of Rent User
- [x] Update List Rent Room Dashboard
- [x] Update Rent Request Room Dashboard
- [x] Improve Admin Dashboard Template
- [ ] Update README.md
- [x] Refactoring
- [x] Bug Fixs
